# Use Python as base image
FROM python:3.9

# Set the working directory
WORKDIR /app

# Copy everything from local folder to container
COPY . /app

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose port 5001
EXPOSE 5001

# Set environment variables
ENV FLASK_APP=app.py

# Start the Flask application
CMD ["flask", "run", "--host=0.0.0.0", "--port=5001"]
